/**
 * Reusable Icon Picker modal
 */

/**
 * Curated Font Awesome class names (`fal fa-*`) for site storage; preview uses
 * {@link IconPicker}'s `resolveIconClass` (typically fal→fas in extension pages).
 * Sorted alphabetically for the grid.
 */
export const ICON_PICKER_ICONS = Object.freeze(
    Array.from(
        new Set([
            'fal fa-address-book',
            'fal fa-address-card',
            'fal fa-air-freshener',
            'fal fa-align-center',
            'fal fa-align-justify',
            'fal fa-align-left',
            'fal fa-align-right',
            'fal fa-anchor',
            'fal fa-angles-down',
            'fal fa-angles-left',
            'fal fa-angles-right',
            'fal fa-angles-up',
            'fal fa-archway',
            'fal fa-arrow-down',
            'fal fa-arrow-down-short-wide',
            'fal fa-arrow-down-wide-short',
            'fal fa-arrow-left',
            'fal fa-arrow-pointer',
            'fal fa-arrow-right',
            'fal fa-arrow-right-arrow-left',
            'fal fa-arrow-rotate-left',
            'fal fa-arrow-rotate-right',
            'fal fa-arrow-trend-down',
            'fal fa-arrow-trend-up',
            'fal fa-arrow-up',
            'fal fa-arrow-up-from-bracket',
            'fal fa-arrow-up-right-from-square',
            'fal fa-arrows-left-right',
            'fal fa-arrows-rotate',
            'fal fa-arrows-up-down',
            'fal fa-asterisk',
            'fal fa-at',
            'fal fa-atom',
            'fal fa-award',
            'fal fa-baby',
            'fal fa-baby-carriage',
            'fal fa-backward',
            'fal fa-bacon',
            'fal fa-bag-shopping',
            'fal fa-balloon',
            'fal fa-ban',
            'fal fa-bandage',
            'fal fa-bank',
            'fal fa-barcode',
            'fal fa-bars',
            'fal fa-bars-staggered',
            'fal fa-baseball',
            'fal fa-basket-shopping',
            'fal fa-basketball',
            'fal fa-bath',
            'fal fa-battery-empty',
            'fal fa-battery-full',
            'fal fa-battery-half',
            'fal fa-battery-quarter',
            'fal fa-bed',
            'fal fa-beer',
            'fal fa-bell',
            'fal fa-bell-slash',
            'fal fa-bezier-curve',
            'fal fa-bicycle',
            'fal fa-binoculars',
            'fal fa-biohazard',
            'fal fa-birthday-cake',
            'fal fa-bitcoin-sign',
            'fal fa-blender',
            'fal fa-bold',
            'fal fa-bolt',
            'fal fa-bomb',
            'fal fa-book',
            'fal fa-book-atlas',
            'fal fa-book-open',
            'fal fa-book-open-reader',
            'fal fa-bookmark',
            'fal fa-bookmark-slash',
            'fal fa-border-all',
            'fal fa-bowl-food',
            'fal fa-box',
            'fal fa-box-archive',
            'fal fa-box-open',
            'fal fa-braille',
            'fal fa-brain',
            'fal fa-bread-slice',
            'fal fa-bridge',
            'fal fa-briefcase',
            'fal fa-broom',
            'fal fa-brush',
            'fal fa-bug',
            'fal fa-building',
            'fal fa-building-columns',
            'fal fa-bullhorn',
            'fal fa-bullseye',
            'fal fa-burger',
            'fal fa-bus',
            'fal fa-business-time',
            'fal fa-c',
            'fal fa-cake-candles',
            'fal fa-calculator',
            'fal fa-calendar',
            'fal fa-calendar-check',
            'fal fa-calendar-days',
            'fal fa-calendar-minus',
            'fal fa-calendar-plus',
            'fal fa-calendar-xmark',
            'fal fa-camera',
            'fal fa-camera-retro',
            'fal fa-campground',
            'fal fa-candy-cane',
            'fal fa-car',
            'fal fa-car-battery',
            'fal fa-car-side',
            'fal fa-caravan',
            'fal fa-card-spade',
            'fal fa-caret-down',
            'fal fa-caret-left',
            'fal fa-caret-right',
            'fal fa-caret-up',
            'fal fa-cart-arrow-down',
            'fal fa-cart-flatbed',
            'fal fa-cart-shopping',
            'fal fa-cash-register',
            'fal fa-cat',
            'fal fa-certificate',
            'fal fa-chair',
            'fal fa-chart-area',
            'fal fa-chart-bar',
            'fal fa-chart-column',
            'fal fa-chart-line',
            'fal fa-chart-pie',
            'fal fa-chart-simple',
            'fal fa-check',
            'fal fa-check-double',
            'fal fa-check-to-slot',
            'fal fa-cheese',
            'fal fa-chess',
            'fal fa-chess-bishop',
            'fal fa-chess-king',
            'fal fa-chess-knight',
            'fal fa-chess-pawn',
            'fal fa-chess-queen',
            'fal fa-chess-rook',
            'fal fa-chevron-down',
            'fal fa-chevron-left',
            'fal fa-chevron-right',
            'fal fa-chevron-up',
            'fal fa-child',
            'fal fa-church',
            'fal fa-circle',
            'fal fa-circle-arrow-down',
            'fal fa-circle-arrow-left',
            'fal fa-circle-arrow-right',
            'fal fa-circle-arrow-up',
            'fal fa-circle-check',
            'fal fa-circle-dot',
            'fal fa-circle-down',
            'fal fa-circle-exclamation',
            'fal fa-circle-half-stroke',
            'fal fa-circle-info',
            'fal fa-circle-left',
            'fal fa-circle-minus',
            'fal fa-circle-notch',
            'fal fa-circle-pause',
            'fal fa-circle-play',
            'fal fa-circle-plus',
            'fal fa-circle-question',
            'fal fa-circle-right',
            'fal fa-circle-stop',
            'fal fa-circle-up',
            'fal fa-circle-user',
            'fal fa-circle-xmark',
            'fal fa-city',
            'fal fa-clapperboard',
            'fal fa-clipboard',
            'fal fa-clipboard-check',
            'fal fa-clipboard-list',
            'fal fa-clock',
            'fal fa-clock-rotate-left',
            'fal fa-clone',
            'fal fa-cloud',
            'fal fa-cloud-arrow-down',
            'fal fa-cloud-arrow-up',
            'fal fa-cloud-moon',
            'fal fa-cloud-sun',
            'fal fa-clover',
            'fal fa-code',
            'fal fa-code-branch',
            'fal fa-code-merge',
            'fal fa-coffee',
            'fal fa-cog',
            'fal fa-cogs',
            'fal fa-coins',
            'fal fa-comment',
            'fal fa-comment-dots',
            'fal fa-comment-medical',
            'fal fa-comment-slash',
            'fal fa-comments',
            'fal fa-compact-disc',
            'fal fa-compass',
            'fal fa-compress',
            'fal fa-computer',
            'fal fa-computer-mouse',
            'fal fa-cookie',
            'fal fa-cookie-bite',
            'fal fa-copy',
            'fal fa-copyright',
            'fal fa-couch',
            'fal fa-credit-card',
            'fal fa-crop',
            'fal fa-cross',
            'fal fa-crosshairs',
            'fal fa-crown',
            'fal fa-cube',
            'fal fa-cubes',
            'fal fa-cut',
            'fal fa-d',
            'fal fa-database',
            'fal fa-delete-left',
            'fal fa-democrat',
            'fal fa-desktop',
            'fal fa-dharmachakra',
            'fal fa-diagram-project',
            'fal fa-diamond',
            'fal fa-dice',
            'fal fa-dice-d20',
            'fal fa-dice-d6',
            'fal fa-dice-five',
            'fal fa-dice-four',
            'fal fa-dice-one',
            'fal fa-dice-six',
            'fal fa-dice-three',
            'fal fa-dice-two',
            'fal fa-disease',
            'fal fa-display',
            'fal fa-dna',
            'fal fa-dog',
            'fal fa-dollar-sign',
            'fal fa-dolly',
            'fal fa-door-closed',
            'fal fa-door-open',
            'fal fa-dove',
            'fal fa-download',
            'fal fa-drafting-compass',
            'fal fa-dragon',
            'fal fa-draw-polygon',
            'fal fa-droplet',
            'fal fa-drum',
            'fal fa-drum-steelpan',
            'fal fa-dumbbell',
            'fal fa-dungeon',
            'fal fa-ear-deaf',
            'fal fa-earth-americas',
            'fal fa-earth-asia',
            'fal fa-earth-europe',
            'fal fa-eclipse',
            'fal fa-egg',
            'fal fa-eject',
            'fal fa-elevator',
            'fal fa-ellipsis',
            'fal fa-ellipsis-vertical',
            'fal fa-envelope',
            'fal fa-envelope-circle-check',
            'fal fa-envelope-open',
            'fal fa-envelope-open-text',
            'fal fa-eraser',
            'fal fa-ethernet',
            'fal fa-euro-sign',
            'fal fa-exchange-alt',
            'fal fa-exclamation',
            'fal fa-expand',
            'fal fa-explosion',
            'fal fa-eye',
            'fal fa-eye-dropper',
            'fal fa-eye-low-vision',
            'fal fa-eye-slash',
            'fal fa-face-angry',
            'fal fa-face-laugh',
            'fal fa-face-meh',
            'fal fa-face-smile',
            'fal fa-face-smile-beam',
            'fal fa-face-surprise',
            'fal fa-face-tired',
            'fal fa-fan',
            'fal fa-fast-backward',
            'fal fa-fast-forward',
            'fal fa-faucet',
            'fal fa-fax',
            'fal fa-feather',
            'fal fa-feather-pointed',
            'fal fa-ferry',
            'fal fa-file',
            'fal fa-file-arrow-down',
            'fal fa-file-arrow-up',
            'fal fa-file-audio',
            'fal fa-file-circle-check',
            'fal fa-file-circle-xmark',
            'fal fa-file-code',
            'fal fa-file-contract',
            'fal fa-file-export',
            'fal fa-file-image',
            'fal fa-file-import',
            'fal fa-file-invoice',
            'fal fa-file-invoice-dollar',
            'fal fa-file-lines',
            'fal fa-file-medical',
            'fal fa-file-pdf',
            'fal fa-file-powerpoint',
            'fal fa-file-shield',
            'fal fa-file-signature',
            'fal fa-file-video',
            'fal fa-file-word',
            'fal fa-file-zipper',
            'fal fa-fill',
            'fal fa-fill-drip',
            'fal fa-film',
            'fal fa-filter',
            'fal fa-filter-circle-dollar',
            'fal fa-fingerprint',
            'fal fa-fire',
            'fal fa-fire-burner',
            'fal fa-fire-extinguisher',
            'fal fa-fire-flame-curved',
            'fal fa-flag',
            'fal fa-flag-checkered',
            'fal fa-flask',
            'fal fa-flask-vial',
            'fal fa-floppy-disk',
            'fal fa-florin-sign',
            'fal fa-folder',
            'fal fa-folder-minus',
            'fal fa-folder-open',
            'fal fa-folder-plus',
            'fal fa-folder-tree',
            'fal fa-font',
            'fal fa-football',
            'fal fa-forward',
            'fal fa-forward-fast',
            'fal fa-forward-step',
            'fal fa-frog',
            'fal fa-frown',
            'fal fa-futbol',
            'fal fa-g',
            'fal fa-gamepad',
            'fal fa-gas-pump',
            'fal fa-gauge',
            'fal fa-gauge-high',
            'fal fa-gauge-simple',
            'fal fa-gavel',
            'fal fa-gem',
            'fal fa-ghost',
            'fal fa-gift',
            'fal fa-gifts',
            'fal fa-glass-water',
            'fal fa-glasses',
            'fal fa-globe',
            'fal fa-golf-ball-tee',
            'fal fa-gopuram',
            'fal fa-graduation-cap',
            'fal fa-greater-than',
            'fal fa-grip-lines',
            'fal fa-grip-lines-vertical',
            'fal fa-grip-vertical',
            'fal fa-guarani-sign',
            'fal fa-guitar',
            'fal fa-gun',
            'fal fa-h',
            'fal fa-hammer',
            'fal fa-hamsa',
            'fal fa-hand',
            'fal fa-hand-back-fist',
            'fal fa-hand-dots',
            'fal fa-hand-fist',
            'fal fa-hand-holding',
            'fal fa-hand-holding-dollar',
            'fal fa-hand-holding-heart',
            'fal fa-hand-lizard',
            'fal fa-hand-middle-finger',
            'fal fa-hand-peace',
            'fal fa-hand-pointer',
            'fal fa-hand-scissors',
            'fal fa-hand-sparkles',
            'fal fa-hand-spock',
            'fal fa-hands',
            'fal fa-hands-asl-interpreting',
            'fal fa-hands-clapping',
            'fal fa-hands-holding',
            'fal fa-handshake',
            'fal fa-hanukiah',
            'fal fa-hard-drive',
            'fal fa-hashtag',
            'fal fa-hat-cowboy',
            'fal fa-hat-wizard',
            'fal fa-head-side-cough',
            'fal fa-headphones',
            'fal fa-headset',
            'fal fa-heart',
            'fal fa-heart-pulse',
            'fal fa-heartbeat',
            'fal fa-helicopter',
            'fal fa-helmet-safety',
            'fal fa-hexagon',
            'fal fa-highlighter',
            'fal fa-hippo',
            'fal fa-history',
            'fal fa-hockey-puck',
            'fal fa-holly-berry',
            'fal fa-home',
            'fal fa-home-lg-alt',
            'fal fa-horse',
            'fal fa-horse-head',
            'fal fa-hospital',
            'fal fa-hot-tub-person',
            'fal fa-hotdog',
            'fal fa-hotel',
            'fal fa-hourglass',
            'fal fa-hourglass-end',
            'fal fa-hourglass-half',
            'fal fa-hourglass-start',
            'fal fa-house',
            'fal fa-house-chimney',
            'fal fa-house-medical',
            'fal fa-ice-cream',
            'fal fa-icicles',
            'fal fa-icons',
            'fal fa-id-badge',
            'fal fa-id-card',
            'fal fa-igloo',
            'fal fa-image',
            'fal fa-image-portrait',
            'fal fa-images',
            'fal fa-inbox',
            'fal fa-indent',
            'fal fa-industry',
            'fal fa-infinity',
            'fal fa-info',
            'fal fa-italic',
            'fal fa-j',
            'fal fa-jar',
            'fal fa-jedi',
            'fal fa-joint',
            'fal fa-journal-whills',
            'fal fa-kaaba',
            'fal fa-key',
            'fal fa-keyboard',
            'fal fa-khanda',
            'fal fa-kip-sign',
            'fal fa-kit-medical',
            'fal fa-landmark',
            'fal fa-language',
            'fal fa-laptop',
            'fal fa-laptop-code',
            'fal fa-laptop-file',
            'fal fa-layer-group',
            'fal fa-leaf',
            'fal fa-left-long',
            'fal fa-left-right',
            'fal fa-lemon',
            'fal fa-less-than',
            'fal fa-life-ring',
            'fal fa-lightbulb',
            'fal fa-link',
            'fal fa-link-slash',
            'fal fa-lira-sign',
            'fal fa-list',
            'fal fa-list-check',
            'fal fa-list-ol',
            'fal fa-list-ul',
            'fal fa-location-arrow',
            'fal fa-location-crosshairs',
            'fal fa-location-dot',
            'fal fa-location-pin',
            'fal fa-lock',
            'fal fa-lock-open',
            'fal fa-lungs',
            'fal fa-m',
            'fal fa-magnet',
            'fal fa-magnifying-glass',
            'fal fa-magnifying-glass-arrow-right',
            'fal fa-magnifying-glass-chart',
            'fal fa-magnifying-glass-dollar',
            'fal fa-magnifying-glass-location',
            'fal fa-magnifying-glass-minus',
            'fal fa-magnifying-glass-plus',
            'fal fa-mail-forward',
            'fal fa-mail-reply',
            'fal fa-mail-reply-all',
            'fal fa-male',
            'fal fa-map',
            'fal fa-map-location',
            'fal fa-map-location-dot',
            'fal fa-map-pin',
            'fal fa-marker',
            'fal fa-mars',
            'fal fa-mars-double',
            'fal fa-mars-stroke',
            'fal fa-mars-stroke-right',
            'fal fa-mars-stroke-up',
            'fal fa-mask',
            'fal fa-mask-face',
            'fal fa-medal',
            'fal fa-memory',
            'fal fa-menorah',
            'fal fa-mercury',
            'fal fa-message',
            'fal fa-meteor',
            'fal fa-microchip',
            'fal fa-microphone',
            'fal fa-microphone-slash',
            'fal fa-microscope',
            'fal fa-mill-sign',
            'fal fa-minimize',
            'fal fa-minus',
            'fal fa-mitten',
            'fal fa-mobile',
            'fal fa-mobile-button',
            'fal fa-mobile-screen',
            'fal fa-mobile-screen-button',
            'fal fa-money-bill',
            'fal fa-money-bill-simple',
            'fal fa-money-bill-transfer',
            'fal fa-money-bill-wave',
            'fal fa-money-bills',
            'fal fa-money-check',
            'fal fa-monument',
            'fal fa-moon',
            'fal fa-mortar-pestle',
            'fal fa-mosque',
            'fal fa-motorcycle',
            'fal fa-mountain',
            'fal fa-mug-hot',
            'fal fa-mug-saucer',
            'fal fa-music',
            'fal fa-n',
            'fal fa-naira-sign',
            'fal fa-network-wired',
            'fal fa-neuter',
            'fal fa-newspaper',
            'fal fa-not-equal',
            'fal fa-note-sticky',
            'fal fa-notes-medical',
            'fal fa-o',
            'fal fa-object-group',
            'fal fa-object-ungroup',
            'fal fa-oil-can',
            'fal fa-om',
            'fal fa-otter',
            'fal fa-outdent',
            'fal fa-p',
            'fal fa-pager',
            'fal fa-paint-roller',
            'fal fa-paintbrush',
            'fal fa-palette',
            'fal fa-pallet',
            'fal fa-panorama',
            'fal fa-paper-plane',
            'fal fa-paperclip',
            'fal fa-parachute-box',
            'fal fa-paragraph',
            'fal fa-passport',
            'fal fa-paste',
            'fal fa-pause',
            'fal fa-paw',
            'fal fa-peace',
            'fal fa-pen',
            'fal fa-pen-clip',
            'fal fa-pen-fancy',
            'fal fa-pen-nib',
            'fal fa-pen-ruler',
            'fal fa-pen-to-square',
            'fal fa-pencil',
            'fal fa-people-arrows',
            'fal fa-people-carry-box',
            'fal fa-pepper-hot',
            'fal fa-percent',
            'fal fa-person',
            'fal fa-person-biking',
            'fal fa-person-booth',
            'fal fa-person-dress',
            'fal fa-person-through-window',
            'fal fa-phone',
            'fal fa-phone-flip',
            'fal fa-phone-slash',
            'fal fa-phone-volume',
            'fal fa-photo-film',
            'fal fa-piggy-bank',
            'fal fa-pills',
            'fal fa-pizza-slice',
            'fal fa-place-of-worship',
            'fal fa-plane',
            'fal fa-plane-arrival',
            'fal fa-plane-departure',
            'fal fa-plane-up',
            'fal fa-plate-wheat',
            'fal fa-play',
            'fal fa-plug',
            'fal fa-plus',
            'fal fa-plus-minus',
            'fal fa-podcast',
            'fal fa-poo',
            'fal fa-poo-storm',
            'fal fa-poop',
            'fal fa-power-off',
            'fal fa-prescription',
            'fal fa-prescription-bottle',
            'fal fa-print',
            'fal fa-pump-medical',
            'fal fa-pump-soap',
            'fal fa-puzzle-piece',
            'fal fa-q',
            'fal fa-qrcode',
            'fal fa-question',
            'fal fa-quote-left',
            'fal fa-quote-right',
            'fal fa-quran',
            'fal fa-r',
            'fal fa-radiation',
            'fal fa-rainbow',
            'fal fa-receipt',
            'fal fa-record-vinyl',
            'fal fa-rectangle-ad',
            'fal fa-rectangle-list',
            'fal fa-rectangle-xmark',
            'fal fa-recycle',
            'fal fa-redo',
            'fal fa-registered',
            'fal fa-repeat',
            'fal fa-reply',
            'fal fa-reply-all',
            'fal fa-republican',
            'fal fa-restroom',
            'fal fa-retweet',
            'fal fa-ribbon',
            'fal fa-right-from-bracket',
            'fal fa-right-left',
            'fal fa-right-long',
            'fal fa-right-to-bracket',
            'fal fa-ring',
            'fal fa-road',
            'fal fa-road-barrier',
            'fal fa-robot',
            'fal fa-rocket',
            'fal fa-rotate',
            'fal fa-rotate-left',
            'fal fa-rotate-right',
            'fal fa-route',
            'fal fa-rss',
            'fal fa-ruble-sign',
            'fal fa-rug',
            'fal fa-ruler',
            'fal fa-ruler-combined',
            'fal fa-ruler-horizontal',
            'fal fa-ruler-vertical',
            'fal fa-rupee-sign',
            'fal fa-rupiah-sign',
            'fal fa-s',
            'fal fa-sack-dollar',
            'fal fa-sack-xmark',
            'fal fa-sailboat',
            'fal fa-satellite',
            'fal fa-satellite-dish',
            'fal fa-scale-balanced',
            'fal fa-scale-unbalanced',
            'fal fa-scale-unbalanced-flip',
            'fal fa-school',
            'fal fa-scissors',
            'fal fa-screwdriver',
            'fal fa-screwdriver-wrench',
            'fal fa-scroll',
            'fal fa-scroll-torah',
            'fal fa-sd-card',
            'fal fa-search',
            'fal fa-section',
            'fal fa-seedling',
            'fal fa-server',
            'fal fa-shapes',
            'fal fa-share',
            'fal fa-share-from-square',
            'fal fa-share-nodes',
            'fal fa-sheet-plastic',
            'fal fa-shekel-sign',
            'fal fa-shield',
            'fal fa-shield-cat',
            'fal fa-shield-dog',
            'fal fa-shield-halved',
            'fal fa-shield-virus',
            'fal fa-ship',
            'fal fa-shirt',
            'fal fa-shoe-prints',
            'fal fa-shop',
            'fal fa-shop-lock',
            'fal fa-shower',
            'fal fa-shuffle',
            'fal fa-shuttle-space',
            'fal fa-sign-hanging',
            'fal fa-signal',
            'fal fa-signature',
            'fal fa-signs-post',
            'fal fa-sim-card',
            'fal fa-sink',
            'fal fa-sitemap',
            'fal fa-skull',
            'fal fa-skull-crossbones',
            'fal fa-slash',
            'fal fa-sleigh',
            'fal fa-sliders',
            'fal fa-smog',
            'fal fa-smoking',
            'fal fa-snowflake',
            'fal fa-snowman',
            'fal fa-socks',
            'fal fa-solar-panel',
            'fal fa-sort',
            'fal fa-sort-down',
            'fal fa-sort-up',
            'fal fa-spa',
            'fal fa-spaghetti-monster-flying',
            'fal fa-spell-check',
            'fal fa-spider',
            'fal fa-spinner',
            'fal fa-spiral',
            'fal fa-splotch',
            'fal fa-spoon',
            'fal fa-spray-can',
            'fal fa-spray-can-sparkles',
            'fal fa-square',
            'fal fa-square-arrow-up-right',
            'fal fa-square-binary',
            'fal fa-square-caret-down',
            'fal fa-square-caret-left',
            'fal fa-square-caret-right',
            'fal fa-square-caret-up',
            'fal fa-square-check',
            'fal fa-square-envelope',
            'fal fa-square-full',
            'fal fa-square-minus',
            'fal fa-square-nfi',
            'fal fa-square-parking',
            'fal fa-square-pen',
            'fal fa-square-phone',
            'fal fa-square-plus',
            'fal fa-square-poll-horizontal',
            'fal fa-square-poll-vertical',
            'fal fa-square-root-variable',
            'fal fa-square-rss',
            'fal fa-square-share-nodes',
            'fal fa-square-up-right',
            'fal fa-square-virus',
            'fal fa-square-xmark',
            'fal fa-staff-snake',
            'fal fa-stairs',
            'fal fa-stamp',
            'fal fa-star',
            'fal fa-star-half-stroke',
            'fal fa-star-of-david',
            'fal fa-star-of-life',
            'fal fa-sterling-sign',
            'fal fa-stethoscope',
            'fal fa-stop',
            'fal fa-stopwatch',
            'fal fa-store',
            'fal fa-store-slash',
            'fal fa-street-view',
            'fal fa-strikethrough',
            'fal fa-stroopwafel',
            'fal fa-subscript',
            'fal fa-subway',
            'fal fa-suitcase',
            'fal fa-suitcase-medical',
            'fal fa-suitcase-rolling',
            'fal fa-sun',
            'fal fa-sun-plant-wilt',
            'fal fa-superscript',
            'fal fa-swatchbook',
            'fal fa-synagogue',
            'fal fa-syringe',
            'fal fa-t',
            'fal fa-table',
            'fal fa-table-cells',
            'fal fa-table-cells-large',
            'fal fa-table-columns',
            'fal fa-table-list',
            'fal fa-table-tennis-paddle-ball',
            'fal fa-tablet',
            'fal fa-tablet-button',
            'fal fa-tablet-screen-button',
            'fal fa-tablets',
            'fal fa-tachograph-digital',
            'fal fa-tag',
            'fal fa-tags',
            'fal fa-tape',
            'fal fa-tarp',
            'fal fa-tarp-droplet',
            'fal fa-taxi',
            'fal fa-teeth',
            'fal fa-teeth-open',
            'fal fa-temperature-arrow-down',
            'fal fa-temperature-arrow-up',
            'fal fa-temperature-empty',
            'fal fa-temperature-full',
            'fal fa-temperature-half',
            'fal fa-temperature-high',
            'fal fa-temperature-low',
            'fal fa-temperature-quarter',
            'fal fa-temperature-three-quarters',
            'fal fa-tenge-sign',
            'fal fa-tent',
            'fal fa-tent-arrow-down-to-line',
            'fal fa-tent-arrow-left-right',
            'fal fa-tent-arrow-turn-left',
            'fal fa-tents',
            'fal fa-terminal',
            'fal fa-text-height',
            'fal fa-text-slash',
            'fal fa-text-width',
            'fal fa-thermometer',
            'fal fa-thumbs-down',
            'fal fa-thumbs-up',
            'fal fa-thumbtack',
            'fal fa-ticket',
            'fal fa-ticket-simple',
            'fal fa-timeline',
            'fal fa-toggle-off',
            'fal fa-toggle-on',
            'fal fa-toilet',
            'fal fa-toilet-paper',
            'fal fa-toilet-paper-slash',
            'fal fa-toolbox',
            'fal fa-tooth',
            'fal fa-torii-gate',
            'fal fa-tower-broadcast',
            'fal fa-tower-observation',
            'fal fa-tractor',
            'fal fa-trademark',
            'fal fa-traffic-light',
            'fal fa-trailer',
            'fal fa-train',
            'fal fa-train-subway',
            'fal fa-train-tram',
            'fal fa-transgender',
            'fal fa-trash',
            'fal fa-trash-arrow-up',
            'fal fa-trash-can',
            'fal fa-tree',
            'fal fa-tree-city',
            'fal fa-triangle-exclamation',
            'fal fa-trophy',
            'fal fa-trowel',
            'fal fa-trowel-bricks',
            'fal fa-truck',
            'fal fa-truck-arrow-right',
            'fal fa-truck-droplet',
            'fal fa-truck-fast',
            'fal fa-truck-field',
            'fal fa-truck-front',
            'fal fa-truck-medical',
            'fal fa-truck-monster',
            'fal fa-truck-moving',
            'fal fa-truck-pickup',
            'fal fa-truck-plane',
            'fal fa-truck-ramp-box',
            'fal fa-tty',
            'fal fa-turkish-lira-sign',
            'fal fa-turn-down',
            'fal fa-turn-up',
            'fal fa-tv',
            'fal fa-u',
            'fal fa-umbrella',
            'fal fa-umbrella-beach',
            'fal fa-underline',
            'fal fa-universal-access',
            'fal fa-unlock',
            'fal fa-unlock-keyhole',
            'fal fa-up-down',
            'fal fa-up-down-left-right',
            'fal fa-up-long',
            'fal fa-up-right-and-down-left-from-center',
            'fal fa-up-right-from-square',
            'fal fa-upload',
            'fal fa-user',
            'fal fa-user-astronaut',
            'fal fa-user-check',
            'fal fa-user-clock',
            'fal fa-user-doctor',
            'fal fa-user-gear',
            'fal fa-user-graduate',
            'fal fa-user-group',
            'fal fa-user-injured',
            'fal fa-user-large',
            'fal fa-user-lock',
            'fal fa-user-minus',
            'fal fa-user-ninja',
            'fal fa-user-nurse',
            'fal fa-user-pen',
            'fal fa-user-plus',
            'fal fa-user-secret',
            'fal fa-user-shield',
            'fal fa-user-slash',
            'fal fa-user-tag',
            'fal fa-user-tie',
            'fal fa-user-xmark',
            'fal fa-users',
            'fal fa-users-between-lines',
            'fal fa-users-gear',
            'fal fa-users-line',
            'fal fa-users-rays',
            'fal fa-users-rectangle',
            'fal fa-users-slash',
            'fal fa-users-viewfinder',
            'fal fa-utensils',
            'fal fa-v',
            'fal fa-van-shuttle',
            'fal fa-vault',
            'fal fa-vector-square',
            'fal fa-venus',
            'fal fa-venus-double',
            'fal fa-venus-mars',
            'fal fa-vest',
            'fal fa-vest-patches',
            'fal fa-video',
            'fal fa-video-slash',
            'fal fa-vihara',
            'fal fa-violin',
            'fal fa-virus',
            'fal fa-virus-slash',
            'fal fa-viruses',
            'fal fa-voicemail',
            'fal fa-volleyball',
            'fal fa-volume-high',
            'fal fa-volume-low',
            'fal fa-volume-off',
            'fal fa-volume-xmark',
            'fal fa-vr-cardboard',
            'fal fa-w',
            'fal fa-walkie-talkie',
            'fal fa-wallet',
            'fal fa-wand-magic',
            'fal fa-wand-magic-sparkles',
            'fal fa-wand-sparkles',
            'fal fa-warehouse',
            'fal fa-water',
            'fal fa-water-ladder',
            'fal fa-wave-square',
            'fal fa-weight-hanging',
            'fal fa-weight-scale',
            'fal fa-wheat-awn',
            'fal fa-wheelchair',
            'fal fa-wheelchair-move',
            'fal fa-whiskey-glass',
            'fal fa-wifi',
            'fal fa-wind',
            'fal fa-window-maximize',
            'fal fa-window-minimize',
            'fal fa-window-restore',
            'fal fa-wine-bottle',
            'fal fa-wine-glass',
            'fal fa-wine-glass-empty',
            'fal fa-won-sign',
            'fal fa-worm',
            'fal fa-wrench',
            'fal fa-x',
            'fal fa-x-ray',
            'fal fa-xmark',
            'fal fa-y',
            'fal fa-yen-sign',
            'fal fa-yin-yang',
            'fal fa-z',
            'fal fa-zap',
        ])
    ).sort((a, b) => a.localeCompare(b))
);

class IconPicker {
    constructor(options = {}) {
        this.translate = options.translate || ((key) => key);
        this.resolveIconClass = options.resolveIconClass || ((cls) => cls);
        this.iconPickerCustomInput = null;
        this.onSelect = null;
        this._ensureModal();
    }

    _ensureModal() {
        if (this.modal) return;

        // Reuse existing modal if present (same id as buttons editor to share CSS)
        const existing = document.getElementById('icon-picker-modal');
        if (existing) {
            this.modal = existing;
            this.iconPickerCustomInput = existing.querySelector('.custom-icon-input');
            return;
        }

        // Defer until body is available
        if (!document.body) {
            document.addEventListener('DOMContentLoaded', () => this._ensureModal(), { once: true });
            return;
        }

        const modal = document.createElement('div');
        modal.id = 'icon-picker-modal';
        modal.className = 'icon-picker-modal hidden';

        const modalContent = document.createElement('div');
        modalContent.className = 'icon-picker-content';

        const modalHeader = document.createElement('div');
        modalHeader.className = 'icon-picker-header';

        const title = document.createElement('h3');
        title.textContent = this.translate('button-icon-select');

        const closeBtn = document.createElement('button');
        closeBtn.className = 'icon-picker-close';
        closeBtn.textContent = '×';
        closeBtn.onclick = () => this.close();

        modalHeader.appendChild(title);
        modalHeader.appendChild(closeBtn);

        const iconsGrid = document.createElement('div');
        iconsGrid.className = 'icons-grid';

        const noIconBtn = document.createElement('button');
        noIconBtn.className = 'icon-option';
        noIconBtn.dataset.icon = '';
        noIconBtn.textContent = this.translate('button-icon-none');
        noIconBtn.onclick = () => {
            if (this.iconPickerCustomInput) this.iconPickerCustomInput.value = '';
            this._select('');
        };
        iconsGrid.appendChild(noIconBtn);

        const customWrap = document.createElement('div');
        customWrap.className = 'custom-icon-wrap';
        const customInput = document.createElement('input');
        customInput.type = 'text';
        customInput.placeholder = 'fal fa-...';
        customInput.className = 'custom-icon-input';
        this.iconPickerCustomInput = customInput;
        const customBtn = document.createElement('button');
        customBtn.type = 'button';
        customBtn.textContent = this.translate('button-icon-select');
        customBtn.onclick = () => {
            const cls = (customInput.value || '').trim();
            this._select(cls);
        };
        customWrap.appendChild(customInput);
        customWrap.appendChild(customBtn);
        modalContent.appendChild(customWrap);

        ICON_PICKER_ICONS.forEach((iconClass) => {
            if (!iconClass) return;
            const iconBtn = document.createElement('button');
            iconBtn.className = 'icon-option';
            iconBtn.dataset.icon = iconClass;
            const icon = document.createElement('i');
            icon.className = this.resolveIconClass(iconClass);
            iconBtn.appendChild(icon);
            iconBtn.onclick = () => {
                if (this.iconPickerCustomInput) this.iconPickerCustomInput.value = iconClass;
                this._select(iconClass);
            };
            iconsGrid.appendChild(iconBtn);
        });

        modalContent.appendChild(modalHeader);
        modalContent.appendChild(iconsGrid);
        modal.appendChild(modalContent);

        document.body.appendChild(modal);
        this.modal = modal;

        modal.addEventListener('click', (e) => {
            if (e.target === modal) {
                this.close();
            }
        });
    }

    _bindModalActionsToCurrentInstance() {
        if (!this.modal) return;

        const closeBtn = this.modal.querySelector('.icon-picker-close');
        if (closeBtn) {
            closeBtn.onclick = () => this.close();
        }

        const customBtn = this.modal.querySelector('.custom-icon-wrap button');
        if (customBtn) {
            customBtn.onclick = () => {
                const cls = (this.iconPickerCustomInput?.value || '').trim();
                this._select(cls);
            };
        }

        const iconButtons = this.modal.querySelectorAll('.icon-option');
        iconButtons.forEach((btn) => {
            const iconClass = btn instanceof HTMLElement ? btn.dataset.icon || '' : '';
            btn.onclick = () => {
                if (this.iconPickerCustomInput) this.iconPickerCustomInput.value = iconClass;
                this._select(iconClass);
            };
        });
    }

    open(currentIcon, onSelect) {
        this.onSelect = onSelect;
        if (!this.modal) {
            this._ensureModal();
            // If still not ready, wait for DOMContentLoaded
            if (!this.modal) {
                document.addEventListener('DOMContentLoaded', () => this.open(currentIcon, onSelect), { once: true });
                return;
            }
        }
        this._bindModalActionsToCurrentInstance();
        if (this.iconPickerCustomInput) this.iconPickerCustomInput.value = currentIcon || '';
        this.modal.classList.remove('hidden');
    }

    close() {
        if (this.modal) this.modal.classList.add('hidden');
        this.onSelect = null;
    }

    _select(iconClass) {
        if (typeof this.onSelect === 'function') {
            this.onSelect(iconClass);
        }
        this.close();
    }
}

if (typeof window !== 'undefined') {
    window.IconPicker = IconPicker;
}

export default IconPicker;
